#!/usr/bin/env python3
"""Generate the division-free Q42 log1p midpoint table."""

from pathlib import Path

import mpmath as mp


SCALE = 10**12
RECIP_SHIFT = 32
Q42 = 1 << 42
SEGMENTS = 1024
STEP = SCALE // SEGMENTS
HALF_STEP = STEP // 2


def round_away(value: mp.mpf) -> int:
    if value >= 0:
        return int(mp.floor(value + mp.mpf("0.5")))
    return int(mp.ceil(value - mp.mpf("0.5")))


def render(name: str, ty: str, values: list[int], length: str | None = None) -> str:
    rows = [f"    {value}," for value in values]
    array_length = length or str(len(values))
    return f"pub(crate) const {name}: [{ty}; {array_length}] = [\n" + "\n".join(rows) + "\n];\n"


def main() -> None:
    mp.mp.dps = 80
    logs: list[int] = []
    reciprocals: list[int] = []
    for j in range(SEGMENTS):
        midpoint = SCALE + (2 * j + 1) * HALF_STEP
        logs.append(round_away(mp.log(mp.mpf(midpoint) / SCALE) * SCALE))
        reciprocals.append(round_away(mp.mpf(Q42 << RECIP_SHIFT) / midpoint))

    output = f"""// @generated by scripts/generate_ln_lut.py; do not edit manually.
// Midpoints partition normalized mantissas [1, 2) into {SEGMENTS} equal bins.

pub(crate) const LN_LUT_SEGMENTS: usize = {SEGMENTS};
pub(crate) const LN_LUT_STEP: u128 = {STEP};
pub(crate) const LN_LUT_HALF_STEP: u128 = {HALF_STEP};

"""
    output += render("LN_LUT_MID_LOG", "i64", logs, "LN_LUT_SEGMENTS")
    output += "\n"
    output += render("LN_Q42_RECIP_G32", "i64", reciprocals, "LN_LUT_SEGMENTS")
    Path(__file__).resolve().parents[1].joinpath("src/ln_lut.rs").write_text(output)


if __name__ == "__main__":
    main()
