#!/usr/bin/env python3
"""Generate the shared rounded k*ln(2) range-reduction table."""

from pathlib import Path

import mpmath as mp


SCALE = 10**12
K_MIN = -64
K_MAX = 88


def round_away(value: mp.mpf) -> int:
    if value >= 0:
        return int(mp.floor(value + mp.mpf("0.5")))
    return int(mp.ceil(value - mp.mpf("0.5")))


def main() -> None:
    mp.mp.dps = 80
    values = [
        round_away(mp.mpf(k) * mp.log(2) * SCALE)
        for k in range(K_MIN, K_MAX + 1)
    ]
    rows = "\n".join(f"    {value}," for value in values)
    output = f"""// @generated by scripts/generate_ln2_lut.py; do not edit manually.
// Shared by ln_1p_fixed and expm1_fixed after power-of-two range reduction.

pub(crate) const K_LN2_MIN: i32 = {K_MIN};
pub(crate) const K_LN2_MAX: i32 = {K_MAX};
pub(crate) const K_LN2_ENTRIES: usize = {len(values)};
pub(crate) const K_LN2_RAW: [i64; K_LN2_ENTRIES] = [
{rows}
];
"""
    Path(__file__).resolve().parents[1].joinpath("src/ln2_lut.rs").write_text(output)


if __name__ == "__main__":
    main()
