#!/usr/bin/env python3
"""Generate the division-free raw-Q22/Q43 expm1 reduction tables."""

from pathlib import Path

import mpmath as mp


SCALE = 10**12
RAW_Q22 = SCALE << 22
LN2 = mp.log(2)
R_MIN = -346_573_590_280
STEP = 1 << 29
SEGMENTS = 1292


def round_away(value: mp.mpf) -> int:
    if value >= 0:
        return int(mp.floor(value + mp.mpf("0.5")))
    return int(mp.ceil(value - mp.mpf("0.5")))


def render(name: str, ty: str, values: list[int], length: str | None = None) -> str:
    rows = [f"    {value}," for value in values]
    array_length = length or str(len(values))
    return f"pub(crate) const {name}: [{ty}; {array_length}] = [\n" + "\n".join(rows) + "\n];\n"


def main() -> None:
    mp.mp.dps = 80
    mid_exp_raw_q22 = []
    for j in range(SEGMENTS):
        midpoint_raw = R_MIN + j * STEP + STEP // 2
        mid_exp_raw_q22.append(round_away(mp.exp(mp.mpf(midpoint_raw) / SCALE) * RAW_Q22))

    inv_ln2_q56 = round_away(mp.mpf(1 << 56) / (LN2 * SCALE))
    raw_to_q43_g31 = round_away(mp.mpf(1 << 74) / SCALE)

    output = f"""// @generated by scripts/generate_expm1_lut.py; do not edit manually.

pub(crate) const EXPM1_R_MIN: i64 = {R_MIN};
pub(crate) const EXPM1_LUT_STEP_SHIFT: u32 = 29;
pub(crate) const EXPM1_LUT_STEP: i64 = {STEP};
pub(crate) const EXPM1_LUT_SEGMENTS: usize = {SEGMENTS};
pub(crate) const EXPM1_INV_LN2_Q56: i64 = {inv_ln2_q56};
pub(crate) const EXPM1_RAW_TO_Q43_G31: i64 = {raw_to_q43_g31};

"""
    output += render("EXPM1_MID_EXP_RAW_Q22", "i64", mid_exp_raw_q22, "EXPM1_LUT_SEGMENTS")
    Path(__file__).resolve().parents[1].joinpath("src/expm1_lut.rs").write_text(output)


if __name__ == "__main__":
    main()
