#!/usr/bin/env python3
"""Generate the guarded fixed-point minimax-style normal-CDF coefficients.

The body is split into half-sigma intervals so each polynomial remains both
small and cheap on SBF.  Coefficients carry 23 binary guard bits; Horner's
normalized argument is Q44.  The four tail pieces approximate Phi(-x)
directly, avoiding exp and division in the standalone CDF path.
"""

from pathlib import Path

import mpmath


mpmath.mp.dps = 80

SCALE = 10**12
T_Q = 44
COEFF_GUARD_Q = 23
TAIL_EVAL_EXTRA_Q = 16
TAIL_STORAGE_LEN = 7

BODY_PIECES = [
    ("NORM_CDF_0_05_Q23", mpmath.mpf("0.0"), mpmath.mpf("0.5"), 8),
    ("NORM_CDF_05_10_Q23", mpmath.mpf("0.5"), mpmath.mpf("1.0"), 8),
    ("NORM_CDF_10_15_Q23", mpmath.mpf("1.0"), mpmath.mpf("1.5"), 8),
    ("NORM_CDF_15_20_Q23", mpmath.mpf("1.5"), mpmath.mpf("2.0"), 8),
    ("NORM_CDF_20_25_Q23", mpmath.mpf("2.0"), mpmath.mpf("2.5"), 8),
    ("NORM_CDF_25_30_Q23", mpmath.mpf("2.5"), mpmath.mpf("3.0"), 8),
    ("NORM_CDF_30_35_Q23", mpmath.mpf("3.0"), mpmath.mpf("3.5"), 8),
    ("NORM_CDF_35_40_Q23", mpmath.mpf("3.5"), mpmath.mpf("4.0"), 7),
    ("NORM_CDF_40_45_Q23", mpmath.mpf("4.0"), mpmath.mpf("4.5"), 7),
    ("NORM_CDF_45_50_Q23", mpmath.mpf("4.5"), mpmath.mpf("5.0"), 7),
]

TAIL_PIECES = [
    ("NORM_TAIL_50_55_Q23", mpmath.mpf("5.0"), mpmath.mpf("5.5"), 6),
    ("NORM_TAIL_55_60_Q23", mpmath.mpf("5.5"), mpmath.mpf("6.0"), 5),
    ("NORM_TAIL_60_65_Q23", mpmath.mpf("6.0"), mpmath.mpf("6.5"), 4),
    ("NORM_TAIL_65_70_Q23", mpmath.mpf("6.5"), mpmath.mpf("7.0"), 3),
]

# Sub-raw-unit coefficient refinements align independently fitted intervals at
# raw-input resolution.  They are expressed in guarded coefficient units
# (2^-23 raw output units).  A dense 250,001-point sweep of every body piece
# keeps the final error within 2 ULP after these two seam constraints.
BODY_COEFFICIENT_ADJUSTMENTS = {
    # These are the Q23 equivalents of the fitted Q20 seam refinements. Their
    # real-valued magnitude is unchanged; only the coefficient guard scale grew.
    "NORM_CDF_10_15_Q23": {1: -7_200_000},
    "NORM_CDF_45_50_Q23": {0: -1_101_632},
}


def fit(a, b, degree, tail=False):
    """Return ascending power-basis coefficients for t in [-1, 1]."""
    midpoint = (a + b) / 2
    half_width = (b - a) / 2
    fn = (
        (lambda t: mpmath.ncdf(-(midpoint + half_width * t)) * SCALE)
        if tail
        else (lambda t: mpmath.ncdf(midpoint + half_width * t) * SCALE)
    )
    descending = mpmath.chebyfit(fn, [-1, 1], degree + 1)
    guard = 1 << COEFF_GUARD_Q
    return [int(mpmath.nint(value * guard)) for value in reversed(descending)]


def rust_int(value):
    sign = "-" if value < 0 else ""
    return f"{sign}{abs(value):_d}"


def render_array(name, coefficients):
    lines = ["#[rustfmt::skip]", f"pub(crate) const {name}: [i64; {len(coefficients)}] = ["]
    lines.extend(f"    {rust_int(value)}," for value in coefficients)
    lines.append("];")
    return "\n".join(lines)


def tail_half_raw_cutoff():
    # Beyond this input Phi(-x) rounds from one raw unit to zero.  Verify both
    # neighboring raw inputs so the emitted integer does not depend on a
    # presentation-level rounding choice.
    root = mpmath.findroot(
        lambda x: mpmath.ncdf(-x) * SCALE - mpmath.mpf("0.5"),
        (mpmath.mpf("7.0"), mpmath.mpf("7.3")),
    )
    cutoff = int(mpmath.floor(root * SCALE))
    at_cutoff = mpmath.ncdf(-mpmath.mpf(cutoff) / SCALE) * SCALE
    after_cutoff = mpmath.ncdf(-mpmath.mpf(cutoff + 1) / SCALE) * SCALE
    assert at_cutoff > mpmath.mpf("0.5")
    assert after_cutoff < mpmath.mpf("0.5")
    return cutoff


def render():
    sections = [
        "// @generated by scripts/generate_norm_cdf_coeffs.py; do not edit manually.",
        "// Coefficients carry 23 binary guard bits and use a Q44 normalized argument.",
        "",
        f"pub(crate) const CDF_T_Q: u32 = {T_Q};",
        f"pub(crate) const CDF_COEFF_GUARD_Q: u32 = {COEFF_GUARD_Q};",
        f"pub(crate) const CDF_TAIL_EVAL_EXTRA_Q: u32 = {TAIL_EVAL_EXTRA_Q};",
        "",
    ]
    for name, a, b, degree in BODY_PIECES:
        coefficients = fit(a, b, degree)
        for index, adjustment in BODY_COEFFICIENT_ADJUSTMENTS.get(name, {}).items():
            coefficients[index] += adjustment
        sections.extend((render_array(name, coefficients), ""))
    for name, a, b, degree in TAIL_PIECES:
        coefficients = fit(a, b, degree, tail=True)
        coefficients.extend([0] * (TAIL_STORAGE_LEN - len(coefficients)))
        sections.extend((render_array(name, coefficients), ""))
    sections.append(
        "pub(crate) const NORM_TAIL_HALF_RAW_CUTOFF: i128 = "
        f"{rust_int(tail_half_raw_cutoff())};"
    )
    return "\n".join(sections) + "\n"


def main():
    destination = Path(__file__).resolve().parents[1] / "src" / "norm_cdf_coeffs.rs"
    destination.write_text(render())
    print(f"wrote {destination}")


if __name__ == "__main__":
    main()
