#!/usr/bin/env python3
"""Generate the compact N32/Q22 coefficient kernel for ``exp_fixed_i``.

The local polynomial is the degree-5 real minimax approximation to ``exp`` on
``[-ln(2)/64, ln(2)/64]``.  A high-precision Remez exchange derives it; the
stored coefficients are then rounded to ``SCALE * 2^22``.  The 32 phase
constants reconstruct ``2^(phase/32)`` at Q62.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import mpmath as mp


ROOT = Path(__file__).resolve().parents[1]
DESTINATION = ROOT / "src" / "exp_coeffs.rs"
SCALE = 10**12
LN2_RAW = 693_147_180_560
PHASE_BITS = 5
PHASES = 1 << PHASE_BITS
POLY_GUARD = 22
POLY_DEGREE = 5
WORK_DPS = 120


def round_away(value: mp.mpf) -> int:
    """Round to nearest, with exact half cases away from zero."""
    if value >= 0:
        return int(mp.floor(value + mp.mpf("0.5")))
    return int(mp.ceil(value - mp.mpf("0.5")))


def solve_exchange(extrema: list[mp.mpf], degree: int) -> tuple[list[mp.mpf], mp.mpf]:
    matrix = mp.matrix(degree + 2, degree + 2)
    target = mp.matrix(degree + 2, 1)
    for row, x in enumerate(extrema):
        for power in range(degree + 1):
            matrix[row, power] = x**power
        matrix[row, degree + 1] = (-1) ** row
        target[row, 0] = mp.exp(x)
    solution = mp.lu_solve(matrix, target)
    return [solution[index, 0] for index in range(degree + 1)], solution[degree + 1, 0]


def derivative_roots(
    coefficients: list[mp.mpf], radius: mp.mpf, degree: int
) -> list[mp.mpf]:
    def derivative_error(x: mp.mpf) -> mp.mpf:
        return (
            sum(
                power * coefficients[power] * x ** (power - 1)
                for power in range(1, degree + 1)
            )
            - mp.exp(x)
        )

    grid = [-radius + 2 * radius * index / 4096 for index in range(4097)]
    values = [derivative_error(x) for x in grid]
    roots: list[mp.mpf] = []
    for left, right, f_left, f_right in zip(grid, grid[1:], values, values[1:]):
        if f_left * f_right < 0:
            root = mp.findroot(derivative_error, (left, right), verify=False)
            if not roots or abs(root - roots[-1]) > mp.mpf("1e-90"):
                roots.append(root)
    assert len(roots) == degree, (len(roots), degree)
    return roots


def derive_remez() -> tuple[list[mp.mpf], mp.mpf, list[mp.mpf]]:
    """Return ascending power coefficients, alternation error and extrema."""
    mp.mp.dps = WORK_DPS
    radius = mp.log(2) / (2 * PHASES)
    extrema = sorted(
        radius * mp.cos(mp.pi * index / (POLY_DEGREE + 1))
        for index in range(POLY_DEGREE + 2)
    )
    for _ in range(30):
        coefficients, error = solve_exchange(extrema, POLY_DEGREE)
        updated = [-radius]
        updated.extend(derivative_roots(coefficients, radius, POLY_DEGREE))
        updated.append(radius)
        movement = max(abs(left - right) for left, right in zip(extrema, updated))
        extrema = updated
        if movement < mp.mpf("1e-100"):
            break
    else:  # pragma: no cover - deterministic convergence guard
        raise AssertionError("Remez exchange did not converge")

    coefficients, error = solve_exchange(extrema, POLY_DEGREE)
    alternating = [
        sum(coefficient * x**power for power, coefficient in enumerate(coefficients))
        - mp.exp(x)
        for x in extrema
    ]
    magnitudes = [abs(value) for value in alternating]
    assert max(magnitudes) - min(magnitudes) < mp.mpf("1e-100")
    assert all(left * right < 0 for left, right in zip(alternating, alternating[1:]))
    return coefficients, abs(error), extrema


def rust_int(value: int) -> str:
    sign = "-" if value < 0 else ""
    return f"{sign}{abs(value):_d}"


def render() -> str:
    mp.mp.dps = WORK_DPS
    ln2 = mp.log(2)
    coefficients, _, _ = derive_remez()
    guarded_scale = SCALE << POLY_GUARD
    quantized = [round_away(value * guarded_scale) for value in coefficients]
    quantized.reverse()
    phases = [round_away(mp.power(2, mp.mpf(index) / PHASES) * (1 << 62)) for index in range(PHASES)]

    raw_to_q64 = mp.mpf(1 << 64) / SCALE
    raw_to_q63_hi = int(mp.floor(raw_to_q64))
    raw_to_q63_frac_q28 = round_away((raw_to_q64 - raw_to_q63_hi) * (1 << 28))
    ln2_residual_q96 = round_away((ln2 - mp.mpf(LN2_RAW) / SCALE) * (1 << 96))
    step_q63 = round_away(ln2 / PHASES * (1 << 63))

    rows = [
        "// @generated by scripts/generate_exp_coeffs.py; do not edit manually.",
        "",
        "/// Split multiplier for converting a raw SCALE residual to Q63 without a",
        "/// wide multiply. Together these approximate `2^64 / SCALE`.",
        f"pub(crate) const EXP_RAW_TO_Q63_HI: i64 = {rust_int(raw_to_q63_hi)};",
        f"pub(crate) const EXP_RAW_TO_Q63_FRAC_Q28: i64 = {rust_int(raw_to_q63_frac_q28)};",
        "",
        "/// `round((ln(2) - LN2_I / SCALE) * 2^96)`.",
        f"pub(crate) const EXP_LN2_RESIDUAL_Q96: i64 = {rust_int(ln2_residual_q96)};",
        "",
        "/// `round((ln(2) / 32) * 2^63)`.",
        f"pub(crate) const EXP_STEP_Q63: i64 = {rust_int(step_q63)};",
        "",
        f"pub(crate) const EXP_POLY_GUARD: i32 = {POLY_GUARD};",
        f"pub(crate) const EXP_PHASE_BITS: i32 = {PHASE_BITS};",
        "pub(crate) const EXP_PHASES: usize = 1 << EXP_PHASE_BITS;",
        "",
        "/// Degree-5 near-minimax coefficients for exp(r) on",
        "/// `[-ln(2)/64, ln(2)/64]`, descending, at `SCALE * 2^22`.",
        "pub(crate) const EXP_REMEZ_Q22: [i64; 6] = [",
    ]
    rows.extend(f"    {rust_int(value)}," for value in quantized)
    rows.extend(
        [
            "];",
            "",
            "/// `round(2^(phase/32) * 2^62)`. These are reconstruction constants,",
            "/// not sampled values of the exponential kernel.",
            "pub(crate) const EXP2_PHASE_Q62: [i64; EXP_PHASES] = [",
        ]
    )
    rows.extend(f"    {rust_int(value)}," for value in phases)
    rows.extend(["];", ""])
    return "\n".join(rows)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the checked-in source differs")
    parser.add_argument("--stdout", action="store_true", help="print instead of writing the source")
    args = parser.parse_args()
    output = render()
    if args.stdout:
        print(output, end="")
    elif args.check:
        assert DESTINATION.read_text() == output, f"{DESTINATION} is stale"
        print(f"verified {DESTINATION}")
    else:
        DESTINATION.write_text(output)
        print(f"wrote {DESTINATION}")


if __name__ == "__main__":
    main()
