name: ci

on:
  push:
  pull_request:

jobs:
  msrv:
    name: msrv library check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.79.0
      - run: cargo check --lib --all-features

  test:
    name: test and package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: git diff --check
      - run: cargo test --no-default-features
      - run: cargo test
      - run: cargo test --all-features
      - run: cargo check --examples --all-features
      - run: cargo package
